CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CakeTemplates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Category" text NOT NULL,
        "IsPopular" boolean NOT NULL,
        "Tiers" integer NOT NULL,
        "BasePrice" numeric(10,2) NOT NULL,
        "MinPrepHours" integer NOT NULL,
        "MaxPrepHours" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CakeTemplates" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Decorations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Category" character varying(100),
        "ImageUrl" text,
        "Price" numeric(18,2) NOT NULL,
        "Occasion" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Decorations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "PhoneVerifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PhoneNumber" text NOT NULL,
        "OtpHash" text NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsVerified" boolean NOT NULL,
        "Attempts" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PhoneVerifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Role" text NOT NULL,
        "Phone" text,
        "Address" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CakeTemplateColors" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CakeTemplateId" integer NOT NULL,
        "ColorName" text NOT NULL,
        "ColorHex" text NOT NULL,
        CONSTRAINT "PK_CakeTemplateColors" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CakeTemplateColors_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CakeTemplateFeatures" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CakeTemplateId" integer NOT NULL,
        "FeatureName" text NOT NULL,
        CONSTRAINT "PK_CakeTemplateFeatures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CakeTemplateFeatures_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CakeTemplateImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CakeTemplateId" integer NOT NULL,
        "ImageUrl" text NOT NULL,
        "TierCount" integer,
        "ImageType" text NOT NULL,
        CONSTRAINT "PK_CakeTemplateImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CakeTemplateImages_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CakeTemplateSizes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CakeTemplateId" integer NOT NULL,
        "SizeInInches" integer NOT NULL,
        CONSTRAINT "PK_CakeTemplateSizes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CakeTemplateSizes_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Cakes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "StockQuantity" integer NOT NULL,
        "ImageUrl" text NOT NULL,
        "IsAvailable" boolean NOT NULL,
        "DesignType" text NOT NULL,
        "IsFeatured" boolean NOT NULL,
        "IsBestSeller" boolean NOT NULL,
        "IsTrending" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "CategoryId" integer NOT NULL,
        CONSTRAINT "PK_Cakes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Cakes_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Carts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer,
        "OrderDate" timestamp with time zone NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "Status" text NOT NULL,
        "CustomerName" text,
        "PhoneNumber" text,
        "ShippingAddress" text,
        "PaymentMethod" text NOT NULL,
        "PaymentStatus" text NOT NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "CartItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CartId" integer NOT NULL,
        "CakeId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "CakeTemplateId" integer,
        "CustomUnitPrice" numeric(18,2),
        "CustomizationJson" text,
        CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CartItems_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_CartItems_Cakes_CakeId" FOREIGN KEY ("CakeId") REFERENCES "Cakes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId") REFERENCES "Carts" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE TABLE "OrderItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "CakeId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        "UnitPrice" numeric(18,2) NOT NULL,
        "Subtotal" numeric(18,2) NOT NULL,
        "CakeTemplateId" integer,
        "CustomizationJson" text,
        CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OrderItems_CakeTemplates_CakeTemplateId" FOREIGN KEY ("CakeTemplateId") REFERENCES "CakeTemplates" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_OrderItems_Cakes_CakeId" FOREIGN KEY ("CakeId") REFERENCES "Cakes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_Cakes_CategoryId" ON "Cakes" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CakeTemplateColors_CakeTemplateId" ON "CakeTemplateColors" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CakeTemplateFeatures_CakeTemplateId" ON "CakeTemplateFeatures" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CakeTemplateImages_CakeTemplateId" ON "CakeTemplateImages" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CakeTemplates_Name" ON "CakeTemplates" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CakeTemplateSizes_CakeTemplateId" ON "CakeTemplateSizes" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_CakeId" ON "CartItems" ("CakeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_CakeTemplateId" ON "CartItems" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_CartItems_CartId" ON "CartItems" ("CartId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Carts_UserId" ON "Carts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Decorations_Name" ON "Decorations" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_CakeId" ON "OrderItems" ("CakeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_CakeTemplateId" ON "OrderItems" ("CakeTemplateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20261008183419_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20261008183419_InitialCreate', '10.0.11');
    END IF;
END $EF$;
COMMIT;

